# Generated by Django 3.2.9 on 2022-03-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220315_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_content', models.CharField(max_length=100)),
                ('long_content', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='posts/Brand/%Y/%m/%d')),
                ('hompage', models.CharField(max_length=200)),
            ],
        ),
    ]
