# Generated by Django 3.2.9 on 2022-03-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='hompage',
            new_name='homepage',
        ),
    ]
