# Generated by Django 3.2.9 on 2022-04-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_hompage_brand_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='problem',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
