# Generated by Django 3.2.9 on 2022-04-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_brand_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/Brand/%Y/%m/%d'),
        ),
    ]
