# Generated by Django 3.2.9 on 2022-04-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.problem'),
        ),
    ]
