# Generated by Django 3.2.9 on 2022-04-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_brand_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='short_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
