# Generated by Django 3.2.9 on 2022-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220422_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
