# Generated by Django 3.2.9 on 2022-05-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220404_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='problem',
            field=models.CharField(default='disabled', max_length=100, null=True),
        ),
    ]
